"""add_search_vector

Revision ID: 69f40f7fd170
Revises: 90d866c9d666
Create Date: 2026-06-26 00:20:57.593173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "69f40f7fd170"
down_revision: Union[str, Sequence[str], None] = "90d866c9d666"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_tasks", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True)
    )
    op.execute("""
UPDATE user_tasks
SET search_vector =
    setweight(
        to_tsvector(
            'english',
            coalesce(title,'')
        ),
        'A'
    )
    ||
    setweight(
        to_tsvector(
            'english',
            coalesce(description,'')
        ),
        'B'
    );
""")
    op.execute("""
CREATE INDEX idx_tasks_search_vector
ON user_tasks
USING GIN(search_vector);
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_tasks", "search_vector")
    op.execute("""
DROP INDEX IF EXISTS idx_tasks_search_vector;
""")
    # ### end Alembic commands ###
