"""remove test column

Revision ID: 765d64d4a405
Revises: 908f08521a72
Create Date: 2026-06-20 01:53:13.086938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765d64d4a405'
down_revision: Union[str, Sequence[str], None] = '908f08521a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'test_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('test_column', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
