"""remove_is_completed

Revision ID: 90d866c9d666
Revises: 05fccbf4afcf
Create Date: 2026-06-23 20:29:10.226934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d866c9d666'
down_revision: Union[str, Sequence[str], None] = '05fccbf4afcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
